//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using WS1.Controllers;

    public partial class contacte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contacte()
        {

            this.email = new HashSet<email>();
            this.telefon = new HashSet<telefon>();
        }
    
        public int contacteId { get; set; }
        public string nom { get; set; }
        public string cognoms { get; set; }
        public bool ShouldSerializetelefon() {

            return true;
        }
        public bool ShouldSerializeemail()
        {

           return true;
        }

        [JsonIgnore,System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<email> email { get; set; }
        [JsonIgnore,System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<telefon> telefon { get; set; }
    } 
}
