'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class contacte
    Public Property contacteId As Integer
    Public Property nom As String
    Public Property cognoms As String

    Public Overridable Property email As ICollection(Of email) = New HashSet(Of email)
    Public Overridable Property telefon As ICollection(Of telefon) = New HashSet(Of telefon)

End Class
